### ISSUE TITLE
Translation of button

### ISSUE THREAD

**Issue by hartenthaler** [JustCarmen/webtrees-fancy-treeview#102] opened 2022-12-15 23:12 UTC
![Screenshot (126)](https://user-images.githubusercontent.com/6324175/207986201-be233bd4-da75-48a9-9551-c25cfe9fabd5.png)

Instead of "Zeigen vorfahren" it should be "Zeige Vorfahren" or much better "Vorfahren anzeigen". I did not find this string in the translation table.

**Comment by hartenthaler** [comment] 2022-12-15 23:20
And it is the same for the button "Zeigen nachkommen".

It should be "Nachkommen anzeigen".

**Comment by Jefferson49** [comment] 2022-12-16 18:07
I have also observed this issue. It is very simular to #93, which I reported earlier and which was fixed with https://github.com/JustCarmen/webtrees-fancy-treeview/commit/e0da23f3b3750ded4ecc0d9fc344c8f8691ac3fd.

#102 appears in the tab "Descendants and ancestors" (see screenshot), while #93 appeared after opening the menu at the top.



![fancy_Zeigen_vorfahren](https://user-images.githubusercontent.com/81484983/208161262-5e12f49d-964d-40df-80ce-c58b31edfc6f.JPG)

**Comment by JustCarmen** [comment] 2022-12-16 19:55
I cannot reproduce this. The string is correctly translated:

https://poeditor.com/projects/po_edit?per_page=20&id=564845&id_language=55&filter=&order=&search=show+ancestors

When I set the language on German the button shows the correct text:

![image](https://user-images.githubusercontent.com/5641963/208178209-ecd43d2b-9602-4020-9116-7c85682289f3.png)

Are you using the latest compiled (mo) file? It is in the zip of the latest beta release.

**Comment by Jefferson49** [comment] 2022-12-16 20:20
There are 2 different views in the module, where this button is shown. Your screenshot is from the menu (i.e. icon at the top), where the correct German text is shown (this was fixed in https://github.com/JustCarmen/webtrees-fancy-treeview/commit/e0da23f3b3750ded4ecc0d9fc344c8f8691ac3fd). 

However, there is a second view, where the translation is also shown and is still wrong. My screenshot above is from the **individual page** and selecting the tab ""Descendants and ancestors".

**Comment by JustCarmen** [comment] 2022-12-16 20:38
Found it. This is a bug indeed.

**Closed** 2022-12-16 20:44 UTC
Labels: bug
